// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Order
{
    public long OrderId { get; set; }

    public long BuyerId { get; set; }

    public long ListingId { get; set; }

    public DateTime OrderDate { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual User Buyer { get; set; }

    public virtual ICollection<Complaint> Complaints { get; set; } = new List<Complaint>();

    public virtual Contract Contract { get; set; }

    public virtual Listing Listing { get; set; }

    public virtual Payment Payment { get; set; }

    public virtual Review Review { get; set; }
}